version: '3'

services:
    frontend :
        build : ./frontend
        ports : 
            - "8080:8080"
    
    backend_express :
        build : ./backend
        ports : 
            - "3000:3000"

    backend_flask :
        build : ./backend_flask
        ports : 
            - "5000:5000"


# docker-compose up -d